export const DISPUTE_STATUSES = {
    OPEN: 'OPEN',
    EVIDENCE_COLLECTED: 'EVIDENCE_COLLECTED',
    AUTO_RESOLVED_RIDER_REFUND: 'AUTO_RESOLVED_RIDER_REFUND',
    AUTO_RESOLVED_DRIVER_PAYOUT: 'AUTO_RESOLVED_DRIVER_PAYOUT',
    NEEDS_MANUAL_REVIEW: 'NEEDS_MANUAL_REVIEW',
    WAITING_FOR_USER_RESPONSE: 'WAITING_FOR_USER_RESPONSE',
    RESOLVED_REFUND: 'RESOLVED_REFUND',
    RESOLVED_PAYOUT: 'RESOLVED_PAYOUT',
    RESOLVED_SPLIT: 'RESOLVED_SPLIT',
    ESCALATED: 'ESCALATED',
} as const;

export const OPEN_DISPUTE_STATUSES = [
    DISPUTE_STATUSES.OPEN,
    DISPUTE_STATUSES.EVIDENCE_COLLECTED,
    DISPUTE_STATUSES.NEEDS_MANUAL_REVIEW,
    DISPUTE_STATUSES.WAITING_FOR_USER_RESPONSE,
    DISPUTE_STATUSES.ESCALATED,
] as string[];
