-- AlterEnum
ALTER TYPE "DlVerificationStatus" ADD VALUE IF NOT EXISTS 'IDENTITY_MISMATCH';

-- AlterEnum
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'VEHICLE_IMAGE_FRONT';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'VEHICLE_IMAGE_BACK';
